'apps: marketing':
  - apps/marketing/**

'apps: web': 
  - apps/web/**

'docker': 
  - docker/**

'scripts': 
  - scripts/**

'migrations':
  - packages/prisma/migrations/**/migration.sql

'e2e tests changes':
  - packages/app-tests/e2e/**

'pkg: assets':
  - packages/assets/**

'pkg: email':
  - packages/email/**

'pkg: eslint-config':
  - packages/eslint-config/**

'pkg: lib':
  - packages/lib/**

'pkg: prettier-config':
  - packages/prettier-config/**

'pkg: prisma':
  - packages/prisma/**

'pkg: signing':
  - packages/signing/**

'pkg: tailwind-config':
  - packages/tailwind-config/**

'pkg: trpc':
  - packages/trpc/**

'pkg: tsconfig':
  - packages/tsconfig/**

'pkg: ui':
  - packages/ui/**
