tasks:
  - init: |
      npm i &&
      npm run dx:up &&
      cp .env.example .env &&
      set -a; source .env &&
      sed -i -e "s|http://localhost:3000|$(gp url 3000)|" .env \
             -e "s|http://localhost:3001|$(gp url 3001)|" .env \
             -e "s|http://localhost:9000|$(gp url 9000)|" .env 
    command: npm run d

ports:
  - port: 3000
    visibility: public
    onOpen: open-preview
  - port: 3001
    visibility: public
    onOpen: open-preview
  - port: 9000
    visibility: public
    onOpen: ignore
  - port: 1100
    visibility: private
    onOpen: ignore
  - port: 2500
    visibility: private
    onOpen: ignore
  - port: 54320
    visibility: private
    onOpen: ignore


github:
  prebuilds:
    master: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode
    - Prisma.prisma
    
